playbook:
  goal: Understand structure, content, identifiers, financial components, and transaction handling of incoming pharmacy (Rx) claims data.
  steps:
    - step: file-footprint-determination
      label: Determine the footprint of data coverage for each file
      checks:
        - check: id-current-date
          label: Select the current date from the database so that we know what day it is.
        - check: id-file
          label: Identify unique ID for each file
          dependencies:
            - id-current-date
          description: "Identify the file name or ID that can be used for subsequent analysis of the file footprints and data generating process. If ursa_file_instance_id is available, use that. If not, look for file IDs or file names. Then check to see if there are multiple files that have been ingested. It is often the case on initial integration that only a single historical file has been loaded."
        - check: id-anchor-date
          label: Identify the anchor date for the file, i.e. the date that was used to filter the generated file (e.g., fill date, paid date).
          description: "Anchor dates are typically display clean start and ends, i.e. the first of the month, or consistent spans between beginning and end dates, i.e. 1 month spans for incremental files or rolling 24 month restated files. Potential dates that should be checked include fill date and most often paid date. Before running analysis, make sure to cast any text fields as dates"
          dependencies:
            - id-file
            - id-current-date
        - check: determine-file-footprint
          label: Analyze the contents of each file.
          description: "Now that we have identified the date used to cut the file, we need to understand the coverage of each file based on those dates. Analyze volume of records, count of patients, and sum of dollars. Are there consistent volumes across files? Are there some files that look like one time historical cuts and others that are ongoing incremental files?"
          dependencies:
            - id-anchor-date
            - id-current-date

    - step: rx-core-data-elements
      label: Identify and assess core pharmacy claim data elements.
      checks:
        - check: core-patient-id
          label: Verify presence of patient identifier.
        - check: core-ndc
          label: Verify presence and format of National Drug Code (NDC codes).
          description: "NDC codes often contain dashes or need to be zero-padded to 11 digits. Our standard is to store them as 11-digit zero-padded strings without dashes. Check for their presence in our NDC reference table which is ursa.mi_ursa_core_106"
        - check: core-fill-date
          label: Verify presence and format of fill date.
        - check: core-prescription-date
          label: Verify presence and format of prescription date.
          description: "This value is often not provided"
        - check: core-paid-date
          label: Verify presence and format of paid date.
        - check: core-days-supply
          label: Check presence and reliability of Days Supply.
          description: "Days supply can be negative for reversals, but the absolute values should be within reason, i.e. not more than 180 days typically. Most common values should be 30, 60, and 90 days."
        - check: core-quantity
          label: Check presence and format of Quantity.
          description: "Are there any negative quantities (typically indicative of reversals) or are they all positive?"
        - check: core-prescription-number
          label: Check for presence of prescription or rx number.
          description: "This value is often not provided, but can be useful for data quality checks when available."
        - check: core-fill-number
          label: Check for presence of fill number.
          description: "This value is often not provided, but can be useful for data quality checks when available."
        - check: core-prescribing-provider
          label: Identify prescribing provider information.
          description: "NPI should be present and 10 digits long. In rare cases, DEA or other identifiers may be used."
        - check: core-filling-provider-pharmacy
          label: Identify filling provider (pharmacy) information.
          description: "NPI should be present and 10 digits long. In rare cases, DEA or other identifiers may be used."
        - check: core-partb-vs-partd
          label: Check for indicators if Rx claim is for Part B or Part D covered drugs.
          description: "This is rarely provided, but very useful if it is."


    - step: rx-claim-identification
      label: Determine primary Rx claim identifiers and key linking fields.
      checks:
        - check: id-transaction-claim-number
          label: Identify the primary transaction ID (often called claim number in Rx).
          description: "Pharmacy transactions often use a 'claim number' that acts as a transaction ID."
        - check: id-claim-natural-key-1
          label: If possible, construct a natural key that includes Patient ID, NDC, and Fill Date.
          description: "This compositve key can help identify unique claims when transaction IDs are missing or duplicated."
          dependencies:
            - core-ndc # NDC is part of the composite key
            - core-fill-date # Fill date is part of the composite key
            - core-patient-id # Patient identifier is part of the composite key
        - check: id-claim-natural-key-2
          label: If possible, construct a natural key that includes Patient ID, Rx Number, and Fill Number.
          description: "This compositve key can help identify unique claims when transaction IDs are missing or duplicated."
          dependencies:
            - core-fill-number # Fill number is part of the composite key
            - core-prescription-number # Prescription number is part of the composite key
            - core-patient-id # Patient identifier is part of the composite key
        - check: id-claim-reference-number
          label: Check for claim reference numbers used to link reversed transactions.
          description: "When transactions get reversed, they will sometimes include claims refernce numbers that point back to the original claim number."
        - check: id-transaction-sequence-number
          label: Check for transaction sequence numbers that can be used to order transactions.
          description: "Sometimes this will come through in an explicit field. Other times it could be a suffix on the end of the claim number. One common pattern in pharmacy claims is a claim number that ends with a 999 type suffix and the sequence descends to 998 and downward"

    - step: rx-financial-elements
      label: Assess financial components of Rx claims.
      checks:
        - check: financial-paid-amount
          label: Identify and validate plan paid amounts.
          description: "Do these fields include negative amounts (typically indicative of reversals) or are they all positive? Are there any zero paid amount claims?"
        - check: financial-patient-responsibility
          label: Identify patient responsibility amounts (copay, coinsurance, deductible).
        - check: financial-ingredient-cost
          label: Check for ingredient cost.
        - check: financial-dispensing-fee
          label: Check for dispensing fee.
        - check: financial-sales-tax
          label: Check for sales tax.

    - step: rx-transaction-handling
      label: Analyze and define rules for handling Rx claim transactions, especially duplicates and reversals.
      description: "Pharmacy claims can have multiple transactions for the same event, including original fills, reversals, and adjustments."
      checks:
        - check: transaction-status-codes
          label: Identify distinct transaction status codes (e.g., approved, reversed, reversal).
        - check: transaction-reversals
          label: Check for presence of reversals which could be indicated by negative paid amounts, negative quantities, or specific status codes.
          description: "Reversed transactions often reference the original via a claim reference number. Reversals can have negative dollar amounts."
          dependencies:
            - financial-paid-amount
            - core-quantity
            - transaction-status-codes
        - check: transaction-deduplication-strategy
          label: Define strategy for handling apparent duplicates and linking transactions for the same claim.
          description: "Within the same file, are there multiple records with the same claim id (which we are assuming is the transaction id)? Do any claim IDs include multiple natural keys (Patient ID||NDC||Fill Date or Patient ID||Rx Number||Fill Number)? If that is the case it does not necessarily mean they are duplicates, but they are cases worth surfacing to the engineer."